name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main  # Trigger on push to main
  workflow_dispatch:

jobs:
  build:
    name: Build Jekyll Site
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build the Jekyll site
        run: |
          bundle exec jekyll build --source docs

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: gh-pages
          build_dir: docs/_site  # Ensure this is where Jekyll builds the site
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
