name: Generate Snake Game

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Update Snake Game
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake Animation
        id: snake-gif
        uses: Sutil/snk@main  # Updated to main, if master doesn't exist
        with:
          github_user_name: SahilKhan44  # Ensure this is correct
          svg_out_path: dist/github-contribution-grid-snake.svg
          snake_color: 'blue'

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
     
        with:
          build_dir: ./  # Root directory
          target_branch: output
          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
