name: Generate snake game

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Update Snake Game
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake Animation
        id: snake-gif
        uses: Sutil/snk@master
        with:
          github_user_name: SahilKhan44  # Replace with your GitHub username
          svg_out_path: dist/github-contribution-grid-snake.svg
          snake_color: 'blue'

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

               
   
